# Generated by Django 4.1.5 on 2023-01-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField()),
                ('MemberSince', models.DateField()),
                ('Occupation', models.CharField(max_length=50)),
                ('Income', models.PositiveIntegerField()),
                ('MaritalStatus', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Education', models.CharField(max_length=50)),
                ('NumAccounts', models.PositiveIntegerField()),
                ('AvgAccountValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AvgCreditRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AvgInvestmentRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('NetWorth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalLiabilities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreditScore', models.PositiveIntegerField()),
                ('AccountActive', models.BooleanField()),
            ],
        ),
    ]
